### ISSUE TITLE
Having trouble locating and connecting to the database. 

### ISSUE THREAD

**Issue by brendadetert** [NUKnightLab/sql-mysteries#25]
I'm new to SQL, have had my IT dept install SQLite and SQLiteStudio. Opened studio, went to add database, browsing and I don't don't know how to find it.

**Comment by JoeGermuska** [comment]
It's hard for us to provide support for your specific computer. But also, we've implemented a 100%-web-based version of the mystery at https://mystery.knightlab.com/ so that may be easier.

Alternatively, [here's a direct-download link](https://github.com/NUKnightLab/sql-mysteries/blob/master/sql-murder-mystery.db?raw=true) for the database.  Download that file and note where you've saved it, and then open it using SQLiteStudio.

Further support would have to be something you take up with your IT Department.

**Comment by brendadetert** [comment]
Thank you!
